// Data to be mapped with back-end drf models
const menuData = [
    {
        dropdownDetails: [
            { 
            title: 'Rainbow_Burgers',
            name: 'Aurantius (Carrot)',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten and Carrots added as topping -for a tastier outcome',
            price: '5.55',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734934/react_app_ourmenu/Burgers_abpltv.jpg',
            },
            { 
            title: 'Rainbow_Burgers',
            name: 'Chiorus (Avocado)',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten and Avocado added as topping -for a tastier outcome',
            price: '5.55',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734934/react_app_ourmenu/Burgers_abpltv.jpg',
            },
            { 
            title: 'Rainbow_Burgers',
            name:  'Flavus (Paprika)',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten and Yellow Paprika added as topping -for a tastier outcome',
            price: '5.55',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734934/react_app_ourmenu/Burgers_abpltv.jpg',
            },   
            { 
            title: 'Rainbow_Burgers',
            name:   'Purpureus (Aubergine)',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten and Aubergine added as topping -for a tastier outcome',
            price: '5.55',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734934/react_app_ourmenu/Burgers_abpltv.jpg',
            },     
            { 
            title: 'Rainbow_Burgers',
            name:   'Roseus (pickled red onion)',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten and Pickled Red Onion added as topping -for a tastier outcome',
            price: '5.55',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734934/react_app_ourmenu/Burgers_abpltv.jpg',
            },  
            { 
            title: 'Rainbow_Burgers',
            name:   'Ruber (Tomato)',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten and Tomato added as topping -for a tastier outcome',
            price: '5.55',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734934/react_app_ourmenu/Burgers_abpltv.jpg',
            }, 
            { 
            title: 'Rainbow_Burgers',
            name:   'Brunus (all ingredients)',
            description: 'This is one of our favorite burger: Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... Note that this burger has all of our toppings: Carrot, Avocado, Paprika, Aubergine, Tomato and Pickled Red Onion -for a tastier outcome',
            price: '6.55',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734922/react_app_ourmenu/Brutus_all_enqrod.jpg',
            },     
        ],
    },
    {
        dropdownDetails: [
            {
            title: 'No_chicken_Burgers',
            name: 'NC Aurantius (Carrot)',
            description: 'No Cheese and no lactos - Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten and Carrots added as topping -for a tastier outcome',
            price: '5.55',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734933/react_app_ourmenu/No_chicken_burger_yhrqn9.jpg',
            },
            {
            title: 'No_chicken_Burgers',
            name: 'NC Chiorus (Avocado)',
            description: 'No Cheese and no lactos - Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten and Avocado added as topping -for a tastier outcome',
            price: '5.55',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734933/react_app_ourmenu/No_chicken_burger_yhrqn9.jpg',
            },
            {
            title: 'No_chicken_Burgers',
            name:  'NC Flavus (Paprika)',
            description: 'No Cheese and no lactos - Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten and Yellow Paprika added as topping -for a tastier outcome',
            price: '5.55',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734933/react_app_ourmenu/No_chicken_burger_yhrqn9.jpg',
            },   
            {
            title: 'No_chicken_Burgers',
            name:   'NC Purpureus (Aubergine)',
            description: 'No Cheese and no lactos - Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten and Aubergine added as topping -for a tastier outcome',
            price: '5.55',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734933/react_app_ourmenu/No_chicken_burger_yhrqn9.jpg',
            },     
            {
            title: 'No_chicken_Burgers',
            name:   'NC Roseus (pickled red onion)',
            description: 'No Cheese and no lactos - Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten and Pickled Red Onion added as topping -for a tastier outcome',
            price: '5.55',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734933/react_app_ourmenu/No_chicken_burger_yhrqn9.jpg',
            },  
            {
            title: 'No_chicken_Burgers',
            name:   'NC Ruber (Tomato)',
            description: 'No Cheese and no lactos - Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten and Tomato added as topping -for a tastier outcome',
            price: '5.55',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734933/react_app_ourmenu/No_chicken_burger_yhrqn9.jpg',
            }, 
            {
            title: 'No_chicken_Burgers',
            name:   'NC Brunus (all ingredients)',
            description: 'No Cheese and no lactos - This is one of our favorite burger: Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... Note that this burger has all of our toppings: Carrot, Avocado, Paprika, Aubergine, Tomato and Pickled Red Onion -for a tastier outcome',
            price: '6.55',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734933/react_app_ourmenu/No_chicken_burger_yhrqn9.jpg',
            },         
        ],
    },
    {
        dropdownDetails: [
            {
            title: 'No_chicken',
            name:   'Nuggets',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... Seasoned with nice vegitable chicken taste',
            price: '3.33',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734927/react_app_ourmenu/Nuggets_q0i8jf.jpg',
            },       
        ],
    },
    {
        dropdownDetails: [
            {
            title: 'Wraps',
            name:   'Stuffed Potato',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... Stuffed with nice crunchy Potato -for a spicier taste',
            price: '5.55',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734933/react_app_ourmenu/Wraps_a8l65b.jpg',
            }, 
            {
            title: 'Wraps',
            name:   'Stuffed Cauliflower',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... Stuffed with nice crispy Cauliflower -for a spicier taste',
            price: '5.55',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734933/react_app_ourmenu/Wraps_a8l65b.jpg',
            }, 
            {
            title: 'Wraps',
            name:   'Stuffed Union garlic',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... Stuffed with nice crispy Union garlic -for a spicier taste',
            price: '5.55',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734933/react_app_ourmenu/Wraps_a8l65b.jpg',
            },
            {
            title: 'Wraps',
            name:   'Stuffed Lentil',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... Stuffed with Lentil -for a soft, but still spicy Taste',
            price: '5.55',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734933/react_app_ourmenu/Wraps_a8l65b.jpg',
            },      
        ],
    },
    {
        dropdownDetails: [
            {
            title: 'Wraps_Dressings',
            name:   'Coriander',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... All our dip sauces have OatMilk, chickpea spade and tofu as a base - Fresh coriander leaves to enhance flavor',
            price: '1.11',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734931/react_app_ourmenu/Wrap_sauses_rsfshf.jpg',
            }, 
            {
            title: 'Wraps_Dressings',
            name:   'Tomato',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... All our dip sauces have OatMilk, chickpea spade and tofu as a base - Fresh tomato slices to enhance flavor',
            price: '1.11',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734931/react_app_ourmenu/Wrap_sauses_rsfshf.jpg',
            }, 
            {
            title: 'Wraps_Dressings',
            name:   'Onion',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... All our dip sauces have OatMilk, chickpea spade and tofu as a base - Fresh onion slices to enhance flavor',
            price: '1.11',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734931/react_app_ourmenu/Wrap_sauses_rsfshf.jpg',
            },
            {
            title: 'Wraps_Dressings',
            name:   'Ginger',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... All our dip sauces have OatMilk, chickpea spade and tofu as a base - Fresh ginger slices to enhance flavor',
            price: '1.11',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734931/react_app_ourmenu/Wrap_sauses_rsfshf.jpg',
            },
        ],
    },
    {
        dropdownDetails: [
            {
            title: 'Desserts',
            name:   'Chocolate pie',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... Seasoned with Cacao and coconut milk -for a yummy taste',
            price: '2.22',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734928/react_app_ourmenu/Pies_ugllqc.jpg',
            },
            {
            title: 'Desserts',
            name:   'Blueberry pie',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... Seasoned with Blueberries and coconut milk -for a yummy taste',
            price: '2.22',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734928/react_app_ourmenu/Pies_ugllqc.jpg',
            },
            {
            title: 'Desserts',
            name:   'Vanilla pie',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... Seasoned with Vanilla and coconut milk -for a yummy taste',
            price: '2.22',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734928/react_app_ourmenu/Pies_ugllqc.jpg',
            },
            {
            title: 'Desserts',
            name:   'Apple pie',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... Seasoned with Apples and coconut milk -for a yummy taste',
            price: '2.22',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734928/react_app_ourmenu/Pies_ugllqc.jpg',
            },
            {
            title: 'Desserts',
            name:   'Chocolate Ice-cream',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... All our ice creams have coconut milk as a base... Seasoned with Cacao -for a yummy taste',
            price: '2.44',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734925/react_app_ourmenu/Ice_cream_cg4fom.jpg',
            },
            {
            title: 'Desserts',
            name:   'Strawberry Ice-cream',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... All our ice creams have coconut milk as a base... Seasoned with Strawberries -for a yummy taste',
            price: '2.44',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734925/react_app_ourmenu/Ice_cream_cg4fom.jpg',
            },
        ],
    },
    {
        dropdownDetails: [
            {
            title: 'Dip',
            name:   'Ketchup',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... All our dip sauces have OatMilk, chickpea spade and tofu as a base - Seasoned with Tomato',
            price: '1.11',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734930/react_app_ourmenu/Dip_sauses_egx3yd.jpg',
            },
            {
            title: 'Dip',
            name:   'Bearnaise (coco milk)',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... All our dip sauces have OatMilk, chickpea spade and tofu as a base - Seasoned with Bearnaise',
            price: '1.11',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734930/react_app_ourmenu/Dip_sauses_egx3yd.jpg',
            },
            {
            title: 'Dip',
            name:   'Mayonnaise (chickpea)', 
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... All our dip sauces have OatMilk, chickpea spade and tofu as a base - Seasoned with Mayonnaise',
            price: '1.11',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734930/react_app_ourmenu/Dip_sauses_egx3yd.jpg',
            },
            {
            title: 'Dip',
            name:   'Carlic',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... All our dip sauces have OatMilk, chickpea spade and tofu as a base - Seasoned with Garlic',
            price: '1.11',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734930/react_app_ourmenu/Dip_sauses_egx3yd.jpg',
            },
            {
            title: 'Dip',
            name:   'Sweat-n-Sour', 
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... All our dip sauces have OatMilk, chickpea spade and tofu as a base - Seasoned with Sweet and Sour',
            price: '1.11',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734930/react_app_ourmenu/Dip_sauses_egx3yd.jpg',
            },
            {
            title: 'Dip',
            name:   'Cheese (Tofu)',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... All our dip sauces have OatMilk, chickpea spade and tofu as a base',
            price: '1.11',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734930/react_app_ourmenu/Dip_sauses_egx3yd.jpg',
            },
            {
            title: 'Dip',
            name:   'Spicy',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... All our dip sauces have OatMilk, chickpea spade and tofu as a base... This dip sause is Seasoned with Jalapenos',
            price: '1.11',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734930/react_app_ourmenu/Dip_sauses_egx3yd.jpg',
            },
        ],
    },
    {
        dropdownDetails: [
            {
            title: 'Accessories',
            name:   'French Fries',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... Crispy potatos fried in Sunflower oil',
            price: '1.33',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734924/react_app_ourmenu/French_fries_sxsvlr.jpg',
            },
            {
            title: 'Accessories',
            name:   'Salad',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... Mixed salad without allergy-causing substances',
            price: '1.36',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734929/react_app_ourmenu/Salad_bcdkou.jpg',
            },
            {
            title: 'Accessories',
            name:   'Potato Gratin',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... Based on Oat milk, Tofu and Corn - fresh sweetpotatos',
            price: '1.66',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734929/react_app_ourmenu/Potato_gratin_iqsoue.jpg',
            },
            {
            title: 'Accessories',
            name:   'Apples',
            description: 'Fresch Sliced Apples from the plants of Sweden',
            price: '1.11',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734923/react_app_ourmenu/Apple_tz1fri.jpg',
            },
            {
            title: 'Accessories',
            name:   'Ananas',
            description: 'Fresch Sliced Ananas imported from Brazil',
            price: '1.11',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734922/react_app_ourmenu/Ananas_o75ola.jpg',
            },
            {
            title: 'Accessories',
            name:   'Carrots',
            description: 'Fresch Sliced Carrots from the plants of Sweden',
            price: '1.11',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734923/react_app_ourmenu/Carrots_d2xfo7.jpg',
            },
        ],
    },
    {
        dropdownDetails: [
            {
            title: 'Add_ons',
            name:   'Pickles',
            description: 'Fresch Sliced - Salted Pickles from the plants of Sweden',
            price: '1.11',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734928/react_app_ourmenu/Pickles_ayfpd3.jpg',
            },
            {
            title: 'Add_ons',
            name:   'Tomatos',
            description: 'Fresch Sliced - Tomatos from the plants of Sweden',
            price: '1.11',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734931/react_app_ourmenu/Tomatos_bh0ken.jpg',
            },
            {
            title: 'Add_ons',
            name:   'Bacon (Rice paper)',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... Based on Rice Paper',
            price: '1.11',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1691278317/react_app_ourmenu/Bacon_azhfp6.jpg',
            },
            {
            title: 'Add_ons',
            name:   'Cheese (Tofu)',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... Based on Tofu',
            price: '1.11',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1691278670/react_app_ourmenu/Cheese_pxutmr.jpg',
            },
        ],
    },
    {
        dropdownDetails: [
            {
            title: 'Snacks',
            name:   'Chili cheese (Tofu)',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... Based on Tofu and Seasoned with Jalapenos',
            price: '2.22',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734924/react_app_ourmenu/Chilli_cheese_pbx9bu.jpg',
            },
            {
            title: 'Snacks',
            name:   'Mozzarella Buns (Tofu)',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... Based on Tofu and Seasoned with a plantbased mozzarella spice',
            price: '2.22',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734924/react_app_ourmenu/Cheese_buns_xzlmn3.jpg',
            },
            {
            title: 'Snacks',
            name:   'Hot wings (Oumph)',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... Based on Oumph and Seasoned with a nice vegitable chicken taste',
            price: '3.33',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734927/react_app_ourmenu/No_chickenwings_kvgrkk.jpg',
            }, 
        ],
    },
    {
        dropdownDetails: [
            {
            title: 'Drinks',
            name:  'Fanta',
            description: 'All our sodas comes with a 33cl can and paper straw if asked for - Fanta',
            price: '1.22',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734930/react_app_ourmenu/Sodas_vemh6e.jpg',
            },
            {
            title: 'Drinks',
            name:  'Coca-Cola',
            description: 'All our sodas comes with a 33cl can and paper straw if asked for - Coke',
            price: '1.22',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734930/react_app_ourmenu/Sodas_vemh6e.jpg',
            },
            {
            title: 'Drinks',
            name:  'Sprite',
            description: 'All our sodas comes with a 33cl can and paper straw if asked for - Sprite',
            price: '1.22',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734930/react_app_ourmenu/Sodas_vemh6e.jpg',
            },
            {
            title: 'Drinks',
            name:  'Water',
            description: 'Fresh Spring water from the source of northern Sweden.. delivered in 33 cl paper glasses',
            price: '1.11',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734931/react_app_ourmenu/Water_urr6py.jpg',
            },
            {
            title: 'Drinks',
            name:  'Milk (Oat)',
            description: 'Fresh Oat milk produced by farmers in northern Sweden.. delivered in 33 cl paper glasses',
            price: '1.22',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734926/react_app_ourmenu/Milk_n1cvbm.jpg',
            },
            {
            title: 'Drinks',
            name:  'Juice (Apple)',
            description: 'Fresh Apple Juice produced by farmers in northern Sweden.. delivered in 33 cl paper glasses',
            price: '1.22',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734925/react_app_ourmenu/Juices_wpcifh.jpg',
            },
            {
            title: 'Drinks',
            name:  'Juice (Orange)',
            description: 'Fresh Orange Juice produced by farmers in northern Sweden.. delivered in 33 cl paper glasses',
            price: '1.22',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734925/react_app_ourmenu/Juices_wpcifh.jpg',
            },
            {
            title: 'Drinks',
            name:   'Strawberry shake (Coco milk)',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... All our Milk Shakes have coconut milk as a base... Seasoned with Strawberries -for a yummy taste',
            price: '2.22',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734925/react_app_ourmenu/Milkshakes_mptzsk.jpg',
            },
            {
            title: 'Drinks',
            name:   'Chocolate shake (Coco milk)',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... All our Milk Shakes have coconut milk as a base... Seasoned with Cacao -for a yummy taste',
            price: '2.22',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734925/react_app_ourmenu/Milkshakes_mptzsk.jpg',
            },
            {
            title: 'Drinks',
            name:   'Rose hip shake (Coco milk)',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... All our Milk Shakes have coconut milk as a base... Seasoned with Rosee Hip -for a yummy taste',
            price: '2.22',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734925/react_app_ourmenu/Milkshakes_mptzsk.jpg',
            },
            {
            title: 'Drinks',
            name:   'Smoothie (Blueberry)',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... All our Smoothies have coconut milk as a base... Topped with Blueberries -for a yummy taste',
            price: '1.55',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734931/react_app_ourmenu/Smoothies_ftxmn2.jpg',
            },
            {
            title: 'Drinks',
            name:   'smoothie (Rose hip)',
            description: 'Basic Ingredients= Only plants with vegetable oil, no E-topiccs or gluten... All our Smoothies have coconut milk as a base... Topped with Rose Hip -for a yummy taste',
            price: '1.55',
            imageUrl: 'https://res.cloudinary.com/dwyxur7sy/image/upload/v1690734931/react_app_ourmenu/Smoothies_ftxmn2.jpg',
            },
        ],
    },
];

export default menuData;

